import { useEffect, useRef, useState } from 'react';
import { ModelProvider, useModel } from './model/ModelContext';
import { registerSW } from 'virtual:pwa-register';
import { FileMenu } from './components/FileMenu';
import { InstallButton } from './components/InstallButton';
import { navIconBtn } from './components/navStyles';
import { ConfirmDialog } from './components/ConfirmDialog';
import { ModelerView } from './modeler/ModelerView';
import { SimulatorView } from './simulator/SimulatorView';
import { HelpView } from './help/HelpView';
import { ModelsLibrary } from './library/ModelsLibrary';
import { StyleReferenceView } from './styleguide/StyleReferenceView';
import { ThemeSwitcher } from './components/ThemeSwitcher';
import { KeyboardShortcutsOverlay } from './components/KeyboardShortcutsOverlay';
import type { CAModel } from './model/types';
import styles from './App.module.css';

type AppMode = 'modeler' | 'simulator' | 'help' | 'library' | 'styleref';

function AppInner() {
  // Every tab/reload lands on the Library — it's the natural starting point for
  // picking a model to explore or fork.
  const [mode, setMode] = useState<AppMode>('library');
  const { model, isDirty, loadedFileName, loadModel } = useModel();
  // Pending library-load that's waiting for an unsaved-changes confirmation.
  // Holds the requested model so the deferred onConfirm has a closed-over
  // reference; setting to null dismisses the dialog.
  const [pendingLibLoad, setPendingLibLoad] = useState<{ model: CAModel; fileName?: string } | null>(null);
  // Transient load-confirmation toast (auto-dismisses).
  const [toast, setToast] = useState<{ msg: string; action?: { label: string; onClick: () => void } } | null>(null);
  const toastTimer = useRef<number | null>(null);
  const showToast = (msg: string, action?: { label: string; onClick: () => void }) => {
    if (toastTimer.current != null) clearTimeout(toastTimer.current);
    setToast({ msg, action });
    // Action toasts (e.g. "update available — reload") persist until clicked or
    // replaced; plain notifications auto-dismiss.
    if (!action) toastTimer.current = window.setTimeout(() => setToast(null), 3500);
  };
  useEffect(() => () => { if (toastTimer.current != null) clearTimeout(toastTimer.current); }, []);

  // Register the offline service worker (generated by vite-plugin-pwa) + request
  // durable storage. 'prompt' mode surfaces an actionable toast on a new deploy
  // rather than silently reloading mid-session.
  useEffect(() => {
    const updateSW = registerSW({
      immediate: true,
      onOfflineReady() { showToast('GenesisCA is ready to work offline.'); },
      onNeedRefresh() {
        showToast('A new version of GenesisCA is available.', { label: 'Reload', onClick: () => updateSW(true) });
      },
    });
    // Auto-granted once installed; keeps the offline cache from being evicted
    // under disk pressure. Storage durability only — does NOT raise the memory
    // ceiling for large grids (that needs the native Tauri shell).
    navigator.storage?.persist?.().catch(() => {});
  }, []);

  // Keyboard-shortcuts cheat-sheet overlay, surfaced as a navbar `?` button so
  // the (otherwise keyboard-only) action is discoverable from any view. The
  // canvas-fullscreen toggle (F) now lives ON each canvas — GraphEditor's
  // view-toggle cluster and SimulatorView's zoom controls — which dispatch the
  // `genesis-toggle-canvas-fullscreen` event those views already listen for.
  const [shortcutsOpen, setShortcutsOpen] = useState(false);
  // `?` (Shift+/) opens the shortcuts overlay — but not while typing in a field.
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key !== '?') return;
      const t = e.target as HTMLElement | null;
      const tag = t?.tagName;
      if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT' || t?.isContentEditable) return;
      e.preventDefault();
      setShortcutsOpen(o => !o);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);
  /** Shared post-load flow: land in the Simulator, confirm the load. */
  const afterLoad = (modelName: string) => {
    setMode('simulator');
    showToast(`Model "${modelName}" loaded successfully.`);
  };

  const handleLoadLibraryModel = (model: CAModel, fileName?: string) => {
    if (isDirty) { setPendingLibLoad({ model, fileName }); return; }
    loadModel(model, fileName);
    afterLoad(model.properties.name);
  };

  return (
    <div className={styles.app} onContextMenu={e => e.preventDefault()}>
      <nav className={styles.navbar}>
        {/* Left: brand + file/help actions + model name */}
        <div className={styles.navLeft}>
          <img
            className={styles.logo}
            src={`${import.meta.env.BASE_URL}icon.svg`}
            alt=""
            width={22}
            height={22}
            draggable={false}
          />
          <span className={styles.title}>GenesisCA <span className={styles.version}>v1.19.0</span></span>
          <a
            className={styles.githubLink}
            href="https://github.com/rff255/GenesisCA"
            target="_blank"
            rel="noopener noreferrer"
            title="View on GitHub"
          >
            <svg width="20" height="20" viewBox="0 0 16 16" fill="currentColor">
              <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38
                0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52
                -.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2
                -3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82
                .64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08
                2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01
                1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z" />
            </svg>
          </a>
          <FileMenu onNew={() => setMode('modeler')} onLoaded={afterLoad} />
          <button
            className={`${styles.navButton} ${mode === 'help' ? styles.navButtonActive : ''}`}
            onClick={() => setMode('help')}
          >Help</button>
          <span className={styles.modelName}>
            {model.properties.name}
            {loadedFileName && <span className={styles.fileName}> ({loadedFileName})</span>}
            {isDirty && <span className={styles.dirtyIndicator}> *</span>}
          </span>
        </div>

        {/* Center: application modes (Blender-style), centered in the free space */}
        <div className={styles.navCenter}>
          <button
            className={`${styles.navButton} ${mode === 'modeler' ? styles.navButtonActive : ''}`}
            onClick={() => setMode('modeler')}
          >Modeler</button>
          <button
            className={`${styles.navButton} ${mode === 'simulator' ? styles.navButtonActive : ''}`}
            onClick={() => setMode('simulator')}
          >Simulator</button>
          <button
            className={`${styles.navButton} ${mode === 'library' ? styles.navButtonActive : ''}`}
            onClick={() => setMode('library')}
          >Library</button>
        </div>

        {/* Right: app-level controls */}
        <div className={styles.navRight}>
          {import.meta.env.DEV && (
            <button
              className={`${styles.navButton} ${mode === 'styleref' ? styles.navButtonActive : ''}`}
              onClick={() => setMode('styleref')}
            >Style Reference</button>
          )}
          <button
            style={navIconBtn}
            title="Keyboard shortcuts (?)"
            aria-label="Keyboard shortcuts"
            onClick={() => setShortcutsOpen(true)}
          >?</button>
          <ThemeSwitcher />
          <InstallButton onInstalled={() => showToast('GenesisCA installed — available offline.')} />
        </div>
      </nav>
      <main className={styles.content}>
        {mode === 'modeler' && <ModelerView />}
        <div style={{ display: mode === 'simulator' ? 'contents' : 'none' }}>
          <SimulatorView visible={mode === 'simulator'} />
        </div>
        {mode === 'help' && <HelpView />}
        {mode === 'library' && <ModelsLibrary onLoadModel={handleLoadLibraryModel} />}
        {mode === 'styleref' && <StyleReferenceView />}
      </main>
      {pendingLibLoad && (
        <ConfirmDialog
          title="Discard unsaved changes?"
          message="You have unsaved changes that will be lost if you load this library model."
          confirmLabel="Load"
          danger
          onConfirm={() => {
            const p = pendingLibLoad;
            setPendingLibLoad(null);
            loadModel(p.model, p.fileName);
            afterLoad(p.model.properties.name);
          }}
          onCancel={() => setPendingLibLoad(null)}
        />
      )}
      {toast && (
        <div className={styles.toast}>
          <span>{toast.msg}</span>
          {toast.action && (
            <button
              onClick={() => { toast.action!.onClick(); setToast(null); }}
              style={{
                marginLeft: 10, background: 'transparent', border: '1px solid var(--color-accent)',
                color: 'var(--color-accent)', borderRadius: 'var(--radius-md)', padding: '2px 9px',
                cursor: 'pointer', font: 'inherit', fontWeight: 500,
              }}
            >{toast.action.label}</button>
          )}
        </div>
      )}
      <KeyboardShortcutsOverlay open={shortcutsOpen} onClose={() => setShortcutsOpen(false)} />
    </div>
  );
}

export function App() {
  return (
    <ModelProvider>
      <AppInner />
    </ModelProvider>
  );
}
